5.1 DataFrame

5.1.1 the first step to use dataframe

In [1]:
import pandas as pd
df = pd.DataFrame([10,20,30,40],columns=['numbers'],index=['a','b','c','d'])
df

   numbers
a       10
b       20
c       30
d       40

In [2]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [3]:
df.columns

Index(['numbers'], dtype='str')

In [4]:
df.loc['c']

numbers    30
Name: c, dtype: int64

In [6]:
df.loc[['a','d']]

   numbers
a       10
d       40

In [7]:
df.iloc[1:3]

   numbers
b       20
c       30

In [8]:
df.sum()

numbers    100
dtype: int64

In [9]:
df.apply(lambda x: x**2)

   numbers
a      100
b      400
c      900
d     1600

In [10]:
df**2

   numbers
a      100
b      400
c      900
d     1600

In [11]:
df['float'] = (1.5,2.5,3.5,4.5)
df

   numbers  float
a       10    1.5
b       20    2.5
c       30    3.5
d       40    4.5

In [12]:
df['float']
df

   numbers  float
a       10    1.5
b       20    2.5
c       30    3.5
d       40    4.5

In [13]:
df['name'] = pd.DataFrame(['Yves','Sandra','Lilli','Henry'],index=['d','a','b','c'])
df

   numbers  float    name
a       10    1.5  Sandra
b       20    2.5   Lilli
c       30    3.5   Henry
d       40    4.5    Yves

In [23]:
df.loc['y'] = {'numbers':100,'floats':5.75,'name':'JIL'}
df

   numbers  float    name
a       10    1.5  Sandra
b       20    2.5   Lilli
c       30    3.5   Henry
d       40    4.5    Yves
y      100    NaN     JIL

In [24]:
df.dtypes

numbers      int64
float      float64
name           str
dtype: object

In [27]:
df[['numbers','float']].mean()

numbers    40.0
float       3.0
dtype: float64

In [28]:
df[['numbers','float']].std()

numbers    35.355339
float       1.290994
dtype: float64