5.1 DataFrame

5.1.1 the first step to use dataframe

In [1]:
import pandas as pd
df = pd.DataFrame([10,20,30,40],columns=['numbers'],index=['a','b','c','d'])
df

   numbers
a       10
b       20
c       30
d       40

In [2]:
df.index

Index(['a', 'b', 'c', 'd'], dtype='str')

In [3]:
df.columns

Index(['numbers'], dtype='str')

In [4]:
df.loc['c']

numbers    30
Name: c, dtype: int64

In [5]:
df.loc[['a','d']]

   numbers
a       10
d       40

In [6]:
df.iloc[1:3]

   numbers
b       20
c       30

In [7]:
df.sum()

numbers    100
dtype: int64

In [8]:
df.apply(lambda x: x**2)

   numbers
a      100
b      400
c      900
d     1600

In [9]:
df**2

   numbers
a      100
b      400
c      900
d     1600

In [10]:
df['float'] = (1.5,2.5,3.5,4.5)
df

   numbers  float
a       10    1.5
b       20    2.5
c       30    3.5
d       40    4.5

In [11]:
df['float']
df

   numbers  float
a       10    1.5
b       20    2.5
c       30    3.5
d       40    4.5

In [12]:
df['name'] = pd.DataFrame(['Yves','Sandra','Lilli','Henry'],index=['d','a','b','c'])
df

   numbers  float    name
a       10    1.5  Sandra
b       20    2.5   Lilli
c       30    3.5   Henry
d       40    4.5    Yves

In [13]:
df.loc['y'] = {'numbers':100,'floats':5.75,'name':'JIL'}
df

   numbers  float    name
a       10    1.5  Sandra
b       20    2.5   Lilli
c       30    3.5   Henry
d       40    4.5    Yves
y      100    NaN     JIL

In [14]:
df.dtypes

numbers      int64
float      float64
name           str
dtype: object

In [15]:
df[['numbers','float']].mean()

numbers    40.0
float       3.0
dtype: float64

In [16]:
df[['numbers','float']].std()

numbers    35.355339
float       1.290994
dtype: float64

5.1.2 The second step to use Pandas

In [17]:
import numpy as np
np.random.seed(100)
a = np.random.standard_normal((9,4))
a

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])

In [18]:
import pandas as pd
df = pd.DataFrame(a)
df

          0         1         2         3
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163
3 -0.583595  0.816847  0.672721 -0.104411
4 -0.531280  1.029733 -0.438136 -1.118318
5  1.618982  1.541605 -0.251879 -0.842436
6  0.184519  0.937082  0.731000  1.361556
7 -0.326238  0.055676  0.222400 -1.443217
8 -0.756352  0.816454  0.750445 -0.455947

In [19]:
df.columns = ['No1','No2','No3','No4']
df

        No1       No2       No3       No4
0 -1.749765  0.342680  1.153036 -0.252436
1  0.981321  0.514219  0.221180 -1.070043
2 -0.189496  0.255001 -0.458027  0.435163
3 -0.583595  0.816847  0.672721 -0.104411
4 -0.531280  1.029733 -0.438136 -1.118318
5  1.618982  1.541605 -0.251879 -0.842436
6  0.184519  0.937082  0.731000  1.361556
7 -0.326238  0.055676  0.222400 -1.443217
8 -0.756352  0.816454  0.750445 -0.455947

In [20]:
df['No2'].mean()

np.float64(0.701033094145646)

In [21]:
dates = pd.date_range('2019-1-1',periods=9,freq='ME')
dates

DatetimeIndex(['2019-01-31', '2019-02-28', '2019-03-31', '2019-04-30',
               '2019-05-31', '2019-06-30', '2019-07-31', '2019-08-31',
               '2019-09-30'],
              dtype='datetime64[us]', freq='ME')

In [22]:
df.index=dates
df

                 No1       No2       No3       No4
2019-01-31 -1.749765  0.342680  1.153036 -0.252436
2019-02-28  0.981321  0.514219  0.221180 -1.070043
2019-03-31 -0.189496  0.255001 -0.458027  0.435163
2019-04-30 -0.583595  0.816847  0.672721 -0.104411
2019-05-31 -0.531280  1.029733 -0.438136 -1.118318
2019-06-30  1.618982  1.541605 -0.251879 -0.842436
2019-07-31  0.184519  0.937082  0.731000  1.361556
2019-08-31 -0.326238  0.055676  0.222400 -1.443217
2019-09-30 -0.756352  0.816454  0.750445 -0.455947

In [23]:
df.values

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])

In [24]:
np.array(df)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693]])

5.2 fundamental analysis

In [25]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 9 entries, 2019-01-31 to 2019-09-30
Freq: ME
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   No1     9 non-null      float64
 1   No2     9 non-null      float64
 2   No3     9 non-null      float64
 3   No4     9 non-null      float64
dtypes: float64(4)
memory usage: 360.0 bytes

In [26]:
df.describe()

            No1       No2       No3       No4
count  9.000000  9.000000  9.000000  9.000000
mean  -0.150212  0.701033  0.289193 -0.387788
std    0.988306  0.457685  0.579920  0.877532
min   -1.749765  0.055676 -0.458027 -1.443217
25%   -0.583595  0.342680 -0.251879 -1.070043
50%   -0.326238  0.816454  0.222400 -0.455947
75%    0.184519  0.937082  0.731000 -0.104411
max    1.618982  1.541605  1.153036  1.361556

In [27]:
df.sum()

No1   -1.351906
No2    6.309298
No3    2.602739
No4   -3.490089
dtype: float64

In [28]:
df.mean()

No1   -0.150212
No2    0.701033
No3    0.289193
No4   -0.387788
dtype: float64

In [29]:
df.mean(axis=0)

No1   -0.150212
No2    0.701033
No3    0.289193
No4   -0.387788
dtype: float64

In [30]:
df.mean(axis=1)

2019-01-31   -0.126621
2019-02-28    0.161669
2019-03-31    0.010661
2019-04-30    0.200390
2019-05-31   -0.264500
2019-06-30    0.516568
2019-07-31    0.803539
2019-08-31   -0.372845
2019-09-30    0.088650
Freq: ME, dtype: float64

In [31]:
df.cumsum()

                 No1       No2       No3       No4
2019-01-31 -1.749765  0.342680  1.153036 -0.252436
2019-02-28 -0.768445  0.856899  1.374215 -1.322479
2019-03-31 -0.957941  1.111901  0.916188 -0.887316
2019-04-30 -1.541536  1.928748  1.588909 -0.991727
2019-05-31 -2.072816  2.958480  1.150774 -2.110045
2019-06-30 -0.453834  4.500086  0.898895 -2.952481
2019-07-31 -0.269316  5.437168  1.629895 -1.590925
2019-08-31 -0.595554  5.492844  1.852294 -3.034142
2019-09-30 -1.351906  6.309298  2.602739 -3.490089

In [32]:
np.mean(df)

np.float64(0.11305673136774012)

In [33]:
np.log(df)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/internals/blocks.py:347: RuntimeWarning: invalid value encountered in log
  result = func(self.values, **kwargs)

                 No1       No2       No3       No4
2019-01-31       NaN -1.070957  0.142398       NaN
2019-02-28 -0.018856 -0.665106 -1.508780       NaN
2019-03-31       NaN -1.366486       NaN -0.832033
2019-04-30       NaN -0.202303 -0.396425       NaN
2019-05-31       NaN  0.029299       NaN       NaN
2019-06-30  0.481797  0.432824       NaN       NaN
2019-07-31 -1.690005 -0.064984 -0.313341  0.308628
2019-08-31       NaN -2.888206 -1.503279       NaN
2019-09-30       NaN -0.202785 -0.287089       NaN

In [34]:
np.sqrt(abs(df))

                 No1       No2       No3       No4
2019-01-31  1.322787  0.585389  1.073795  0.502430
2019-02-28  0.990616  0.717091  0.470297  1.034429
2019-03-31  0.435311  0.504977  0.676777  0.659669
2019-04-30  0.763934  0.903796  0.820196  0.323127
2019-05-31  0.728890  1.014757  0.661918  1.057506
2019-06-30  1.272392  1.241614  0.501876  0.917843
2019-07-31  0.429556  0.968030  0.854986  1.166857
2019-08-31  0.571173  0.235958  0.471593  1.201340
2019-09-30  0.869685  0.903578  0.866282  0.675238

In [35]:
np.sqrt(abs(df)).sum()

No1    7.384345
No2    7.075190
No3    6.397719
No4    7.538440
dtype: float64

In [36]:
100*df+100

                   No1         No2         No3         No4
2019-01-31  -74.976547  134.268040  215.303580   74.756396
2019-02-28  198.132079  151.421884  122.117967   -7.004333
2019-03-31   81.050417  125.500144   54.197301  143.516349
2019-04-30   41.640495  181.684707  167.272081   89.558886
2019-05-31   46.871962  202.973269   56.186438  -11.831825
2019-06-30  261.898166  254.160517   74.812086   15.756426
2019-07-31  118.451869  193.708220  173.100034  236.155613
2019-08-31   67.376194  105.567601  122.239961  -44.321700
2019-09-30   24.364769  181.645401  175.044476   54.405307